# .streamlit/secrets.toml
[api_keys]
OPENAI_API_KEY="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"
VOYAGE_AI_API_KEY="pa-4wrX-aHYKoPYidJMHsvEFdOisiKDPzIz5ngrGEuxw-U"
PINECONE_API_KEY="e94bdd59-acb8-4806-b66e-d22f50f1f972"
